---
title: "Music terms"
format: html
editor: visual
author:
 - name: "Daniel Antal, CFA"
   orcid: 0000-0001-7513-6760
   affiliations:
     - name: Reprex
       address: "Saturnusstraat 14"
       city: The Hague
       state: Zuid-Holland
       country: The Netherlands
       postal-code: "2516 AH"
       url: https://reprex.nl/
 - name: "Anna Márta Mester"
   orcid: 0009-0008-2274-8163
   affiliations:
       - name: Reprex
         address: "Saturnusstraat 14"
         city: The Hague
         state: Zuid-Holland
         country: The Netherlands
         postal-code: "2516 AH"
         url: https://reprex.nl/
---

## Music concepts {.unnumbered}

| Term | Description |
|----|----|
| `audio recording` | fixation of sounds [@iso_isrc_2019] |
| `work` | distinct, abstract creation of the mind whose existence is revealed through one or more expressions (e.g. a performance) or manifestations (e.g. an object) [@iso_iswc_2022] |
| `musical work` | composed of a combination of sounds, with or without accompanying text [@iso_iswc_2022] |
| `music video recording` | fixation of sounds synchronized with pictures or moving pictures where (a) the fixed sounds are wholly or substantially a musical performance or (b) the *recording* is intended for viewing in association with a recording of a musical performance. This definition includes music videos and concert recordings, together with music-related interviews and documentaries, but does not extend to genera! audiovisual material, even if it includes music.[@iso_isrc_2019] |
| `DSP` or `digital streaming platform` | Digital service providers (DSPs), or Digital Streaming Platforms are companies or organisations that provide access to services online. DSPs can provide access to music downloads, like Apple's iTunes Store, or access to streaming music like Spotify, or even provide satellite-delivered content such as SiriusXM in the USA. |
| `rights management (organisations)` | the function of managing the rights on behalf of rights owners. It can be companies whose sole purpose is to ensure that content that has been licensed has delivered royalties that are identified and accounted for. The role can be taken by collective management organisations or by private companies on behalf of songwriters, composers, performers, music publishers, or record labels. [@iso_isbn_2017] |
| `original version` | The first established form of a work. [@iso_iswc_2022] |
| `composite of samples` | A composite work containing new material and one or more samples of pre-existing recorded works. [@iso_iswc_2022] |
| `medley` | A continuous and sequential combination of existing works or excerpts. [@iso_iswc_2022] |
|  |  |

: Music terms and definitions {tbl-colwidths="\[25,75\]"}

## Titles

| Term | Description |
|----|----|
|  |  |
|  |  |
|  |  |
|  |  |
|  |  |
| `original title` | A title given to the work by its creator(s) shown in its original language. [@iso_iswc_2022] |
| `formal title` | A standardized title in which the elements are arranged in a pre-determined order, such as titles created for classica! works. [@iso_iswc_2022] |
|  |  |

: Music definitions: titles {tbl-colwidths="\[25,75\]"}

## Roles

| Term | Description |
|----|----|
| `arranger` | The author, or one of the authors, of an adapted text of a musical work. [@iso_iswc_2022] |
| `author` | The creator, or one of the creators, of the text of a musical work. [@iso_iswc_2022] Entitled to authors' right or copyright. |
| `composer` | The creator, or one of the creators, of the musical elements of a musical work. [@iso_iswc_2022] Entitled to authors' right or copyright. |
| `lyricist` | The author of the text of a musical work, or a literary text that is arranged together with a musical work. Entitled to authors' right or copyright. |
| `performer` | The performer of a musical work; in case of a sound recording, the performer whose performance is fixed in the recording. They may be entitled to neighbouring or sound recording copyrights. |
| `producer` | The person or legal entity that produces the recorded fixation of the sound recording. They are entitled to neighbouring or sound recording copyrights. |
|  |  |
|  |  |

: Music definitions: names of persons and groups {tbl-colwidths="\[25,75\]"}

## Artis names

| Term | Description |
|----|----|
|  |  |
|  |  |
|  |  |
|  |  |
| `original title` | A title given to the work by its creator(s) shown in its original language. [@iso_iswc_2022] |
| `formal title` | A standardized title in which the elements are arranged in a pre-determined order, such as titles created for classica! works. [@iso_iswc_2022] |
|  |  |

: Music definitions: names of persons and groups {tbl-colwidths="\[25,75\]"}

## Identifiers

| Term      | Description |
|-----------|-------------|
| `ISNI`    |             |
| `ISRC`    |             |
| `ISMM`    |             |
| `ISWC`    |             |
| `VIAF ID` |             |
|           |             |
|           |             |

: Music definitions: identifiers {tbl-colwidths="\[25,75\]"}

## Characteristics

| Term | Description |
|----|----|
| `duration` | The elapsed playing time between the first and last recorded modulations of the recording. |
|  |  |
|  |  |

: Music definitions: identifiers {tbl-colwidths="\[25,75\]"}

## References {.unnumbered}
